tongoza/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
import certbot_django.server.urls

from tongoza import settings

urlpatterns = [
    path('', include('tongozahome.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('friend/', include('friend.urls')),
    path('users/', include('users.urls')),
    path('marketing/', include('marketing.urls')),
    url(r'^\.well-known/', include(certbot_django.server.urls)),


]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [
        url('__debug__/', include(debug_toolbar.urls))
    ]

tongozahome/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.urls import path

from tongoza import settings
from . import views

app_name = 'tongozahome'

urlpatterns = [

    # path('', views.home, name='home'),

    url(r'^$', views.HomeView.as_view(), name='home'),

    path('profile/<slug>/', views.profileDetail, name='profile'),
    path(r'post/<slug>/', views.PostDetailedView.as_view(), name='postView'),
    path(r'post-create/<pk>/', views.PostCreateView.as_view(), name='post_create'),
    path(r'post/<slug>/update', views.PostUpdateView.as_view(), name='post_update'),
    path(r'post/<slug>/delete', views.PostDeleteView.as_view(), name='post_delete'),

    # path('profile/<slug>', views.profile, name='profile'),
    path('search/', views.search_results, name='search'),


    url(r"^profile-images/(?P<slug>[\w-]+)/$", views.show_profile_images, name="profile_images", ),
    url(r'^profile-images/(?P<slug>[\w-]+)/create$', views.ProfileImageCreateView.as_view(),
        name='profile_image_create'),
    # # url(r'^product-images/(?P<slug>[\w-]+)/create$', views.product_image_create, name='product_image_create'),
    url("^profile-image/(?P<pk>[\w-]+)/update/$", views.ProfileImageUpdateView.as_view(), name="profile_image_update"),
    # url('^profile-image-(?P<pk>[\w-]+)/delete/$', views.ProfileImageDeleteView.as_view(), name="profile_image_delete"),
    url('^profile-image-(?P<pk>[\w-]+)/delete/$', views.delete_image, name="profile_image_delete"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.conf.urls import url
# from django.conf.urls import *
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

from . import views

app_name = 'users'

urlpatterns = [
    url("^profile-(?P<slug>[\w-]+)/update/$", views.profileUpdate, name="profile_update", ),

]

tongozahome/models.py
import itertools
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.text import slugify
from stdimage import StdImageField
from django_countries.fields import CountryField
from ckeditor.fields import RichTextField
from utils.models import CreationModificationDateMixin
from phonenumber_field.modelfields import PhoneNumberField
from mptt.models import MPTTModel, TreeForeignKey

# Create your models here.
from tongoza import settings


class ActiveProfileManager(models.Manager):
    def all(self):
        return super(ActiveProfileManager, self).all().filter(is_active=True)


class ProfileManager(models.Manager):
    def get_by_natural_key(self, slug):
        return self.get(slug=slug)


class AbstractProfile(CreationModificationDateMixin):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True, default='', max_length=255, editable=False)
    aboutMe = models.CharField(max_length=400)
    company = models.CharField(max_length=100, blank=True, null=True)
    role = models.CharField(max_length=100, blank=True, null=True)
    education_institution = models.CharField(max_length=200, blank=True, null=True)
    course = models.CharField(max_length=200, blank=True, null=True)
    address = models.CharField(max_length=60, blank=True, null=True)
    linkedin = models.CharField(max_length=150, blank=True, null=True)
    facebook = models.CharField(max_length=150, blank=True, null=True)
    twitter = models.CharField(max_length=150, blank=True, null=True)
    telegram_username = models.CharField(max_length=60, blank=True, null=True)
    snapchat_username = models.CharField(max_length=60, blank=True, null=True)
    messenger = models.CharField(max_length=60, blank=True, null=True)
    whatsapp_phone_number = PhoneNumberField(blank=True, null=True)
    country = CountryField(multiple=False, blank=True, null=True)
    city = models.CharField(max_length=60, blank=True, null=True)
    gender = models.CharField(max_length=1, blank=True, null=True)
    postal_code = models.CharField(max_length=10, blank=True, null=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        abstract = True


class Profile(AbstractProfile):
    government_issued_id = StdImageField(upload_to='tongoza/images/national_identificantions/', blank=True, null=True,
                                         help_text='Required only if you wish to have a dual'
                                                   ' profile for both Tongoza light mode and Tongoza darke mode')

    active = ActiveProfileManager()
    objects = ProfileManager()

    class Meta(AbstractProfile.Meta):
        db_table = 'Light Mode Profile'

    def __str__(self):
        return str(self.user.username)

    def natural_key(self):
        return (self.slug,)

    def get_absolute_url(self):
        return reverse('tongozahome:profile', kwargs={'slug': self.slug})

    def get_image_in_display(self):
        image = self.profileimage_set.filter(in_display=True, dark_mode_pic=False, public=True)
        if image:
            return image[0]

    def get_caption(self):
        image = self.get_image_in_display()
        if image:
            if image.caption:
                return image.caption

    def get_profile_pic(self):
        image = self.profileimage_set.filter(profile_pic=True, dark_mode_pic=False)
        if image:
            return image[0]
        else:
            return self.get_image_in_display()

    def get_dark_profile_pic(self):
        image = self.profileimage_set.filter(profile_pic=True, dark_mode_pic=True)
        if image:
            return image[0]
        else:
            return self.get_image_in_display()

    def get_light_mode_public_images(self):
        images = self.profileimage_set.filter(in_display=False, dark_mode_pic=False, public=True)
        return images

    def get_light_mode_images(self):
        images = self.profileimage_set.filter(in_display=False, dark_mode_pic=False)
        return images

    def get_user_public_posts(self):
        posts = self.post_set.filter(active=True, public=True)
        return posts

    def get_user_all_posts(self):
        posts = self.post_set.filter(active=True)
        return posts

    def _generate_slug(self):
        value = self.user.username
        slug_original = slugify(value, allow_unicode=True)

        slug_candidate = '{}'.format(slug_original)

        return slug_candidate

    def save(self, *args, **kwargs):
        if not self.pk or self.slug != self.user.username:
            print('came to update sluggg')
            self.slug = self._generate_slug()
        if self.get_image_in_display():
            self.is_active = True
        else:
            self.is_active = False

        super().save(*args, **kwargs)


class DisplayImageManager(models.Manager):
    def get_query_set(self):
        return super(DisplayImageManager, self).get_query_set().filter(in_display=True)


class ProfileImage(CreationModificationDateMixin):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    image = StdImageField(upload_to='tongoza/images/profile_images', variations={
        'thumbnail': (250, 250),
        'medium': (420, 236, True),
        'large': (800, 675)
    }, delete_orphans=True)
    caption = models.TextField(blank=True, null=True,
                               help_text="Write something about the moment captured in this image")
    public = models.BooleanField(default=True)
    in_display = models.BooleanField(default=True)
    profile_pic = models.BooleanField(default=True)

    dark_mode_pic = models.BooleanField(default=False)
    displayed = DisplayImageManager()
    objects = models.Manager()

    class Meta:
        ordering = ('-in_display',)

    def __str__(self):
        return str(self.profile)

    def save(self, *args, **kwargs):
        if self.in_display:
            self.profile.active = True
            self.profile.save()

        super().save(*args, **kwargs)


def get_public_posts():
    posts = Post.objects.filter(active=True, public=True)
    return posts


def get_all_posts():
    posts = Post.objects.filter(active=True)
    return posts


class Post(CreationModificationDateMixin):
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    # author = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True)
    slug = models.SlugField(unique=True,
                            default='',
                            editable=False,
                            max_length=255,
                            )
    title = models.CharField(max_length=100)
    image = StdImageField(upload_to='tongoza/posts/images/products',
                          help_text="upload post cover Image",
                          variations={
                              'thumbnail': (250, 250),
                              'medium': (420, 236, True),
                              'large': (800, 675)
                          }, delete_orphans=True)
    caption = models.TextField(help_text="Inspire your audience with the moment captured in this image")
    public = models.BooleanField(default=True, help_text="Everyone can see this post.")

    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='post_likes')
    active = models.BooleanField(default=True)

    def __str__(self):
        return str(self.title)

    def get_total_likes(self):
        return self.likes.count()

    def get_user_all_other_posts(self):
        posts = Post.objects.filter(active=True).exclude(id=self.id)
        return posts

    def get_user_other_public_posts(self):
        posts = Post.objects.filter(active=True, public=True).exclude(id=self.id)
        return posts

    def cross_reads(self):
        # orders = Order.objects.filter(items__item=self)
        # order_items = OrderItem.objects.filter(order__in=orders).exclude(item=self)
        posts = Post.objects.all().exclude(slug=self.slug)
        return posts

    def get_absolute_url(self):

        return reverse('tongozahome:postView', kwargs={'slug': self.slug})

    def _generate_slug(self):
        max_length = self._meta.get_field('slug').max_length
        value = self.title
        slug_candidate = slug_original = slugify(value, allow_unicode=True)
        for i in itertools.count(1):
            if not Post.objects.filter(slug=slug_candidate).exists():
                break
            slug_candidate = '{}-{}'.format(slug_original, i)

        return slug_candidate

    def save(self, *args, **kwargs):
        if not self.pk:
            self.slug = self._generate_slug()

        super().save(*args, **kwargs)


class Comments(MPTTModel):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments', null=True, blank=True)
    parent = TreeForeignKey('self', on_delete=models.CASCADE,
                            null=True, blank=True, related_name='children')
    content = models.TextField()
    publish = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=True)

    class MPTTMeta:
        order_insertion_by = ('publish',)

    def __str__(self):
        return f'Comment by {self.post.author}'

tongozahome/forms.py
from django import forms
from .models import *


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'image', 'caption', 'public']


class PostUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'caption', 'image', 'public']

tongozahome/templates/tongozahome/modelforms/product_image_delete.html
{% extends 'tongozahome/base.html' %}
{% load crispy_forms_tags %}

{% block headblock %}

{% endblock %}

<body>

{% block site_wrapper %}

<div class="super_container">
    <div class=" container content-section mt-5">
        <form method="POST">
<!--                protect form from attacks-->
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Image</legend>
<!--                    Call the form from views-->
                <h2> Are you sure you want to delete image for "{{ object.item }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{{ object.get_absolute_url }} ">Cancel</a>
            </div>
        </form>

    </div>
</div>


{% endblock %}


{% block extra_scripts %}


{% endblock %}
</body>

tongozahome/templates/tongozahome/modelforms/product_image_form.html
{% extends 'me2ushop/base_template.html' %}
{% load crispy_forms_tags %}

{% block headblock %}
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/contact_styles.css">
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/contact_responsive.css">

{% endblock %}


<body>
 {% block navbar %}
 {% endblock %}

{% block site_wrapper %}

<div class="super_container">

	<!-- Cart -->
	<div class="contact_form">
		<div class="container">
			<div class="row">
				<div class="col-lg-10 offset-lg-1">
					<div class="contact_form_container">
						<div class="contact_form_title">Add a new Image</div>

						<form method="POST" enctype="multipart/form-data">
							{% csrf_token %}
	                        {{ form|crispy }}
							<input type="hidden" id="id_slug" value="{{ object.slug }}"/>
							<div class="contact_form_button form-group">
								<button type="submit" class="button contact_submit_button">Submit</button>
								<button class="button danger-color ml-2"><a href="{% url 'me2ushop:product_images' product.slug %}">Cancel</a></button>
							</div>

						</form>

					</div>
				</div>
			</div>
		</div>
		<div class="panel"></div>
	</div>


</div>


{% endblock %}


 {% block footer %}
 {% endblock %}


{% block extra_scripts %}

<script src="{{ STATIC_URL }}js/contact_custom.js"></script>


{% endblock %}
</body>

tongozahome/templates/tongozahome/modelforms/product_images_list.html
{% extends 'me2ushop/base_template.html' %}
{% load mptt_tags %}

{% block headblock %}
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/plugins/jquery-ui-1.12.1.custom/jquery-ui.css">
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/shop_styles.css">
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/shop_responsive.css">

{% endblock %}


<body>

{% block site_wrapper %}

<div class="super_container">

	<!-- Shop -->

	<div class="shop">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">

					<!-- Shop Content -->
					<div class="shop_content">
						<div class="shop_bar clearfix">
							<div class="card card-body">
						       <div class="text-center font-small wow fadeIn">
						           {% if product_image.count < 12 %}
						            <a class="btn btn-outline-secondary" href="{% url 'me2ushop:product_image_create' object.slug %}">Add New Image</a>
						           {% endif %}
						           <a class="btn btn-outline-secondary" href="{% url 'me2ushop:product' object.slug %}">View Product</a>
						            <a class="btn btn-outline-orange" href="{% url 'me2ushop:product-create' brand_id %}"
						               role="button">Add A New Product</a>
						            </a>
						           <a class="btn btn-outline-yellow" href="{{ object.brand_name.get_backstore_url }}">Dashboard</a>

						        </div>
							</div>

							<div class="shop_product_count"><span>{{ product_image.count }}</span> {{ object.title }} Images</div>

						</div>

						<div class="product_grid">
							<div class="product_grid_border"></div>

							<!-- Product Item -->


                            {% for image in product_image %}

							<div class="product_item is_new">
								<div class="product_border"></div>
								<div class="product_image d-flex flex-column align-items-center justify-content-center"><a href="{{object.get_absolute_url}}"><img src="{{ image.image.thumbnail.url }}" alt=""></a></div>
								<div class="product_content">
                                    <div class="product_price"><a href="{% url 'me2ushop:product_image_update' image.id%}">update</a></div>
                                    <div class="product_price"><a href="{% url 'me2ushop:product_image_delete' image.id%}">Delete</a></div>
                                    {% if image.in_display %}

									<div class="product_name"><div><a href="#" tabindex="0">Currently Displayed</a></div></div>

                                    {% endif %}
								</div>
							</div>
                            {% endfor %}

						</div>

						<!-- Shop Page Navigation -->

						<div class="shop_page_nav d-flex flex-row">
							<div class="page_prev d-flex flex-column align-items-center justify-content-center"><i class="fas fa-chevron-left"></i></div>
							<ul class="page_nav d-flex flex-row">
								<li><a href="#">1</a></li>
								<li><a href="#">2</a></li>
								<li><a href="#">3</a></li>
								<li><a href="#">...</a></li>
								<li><a href="#">21</a></li>
							</ul>
							<div class="page_next d-flex flex-column align-items-center justify-content-center"><i class="fas fa-chevron-right"></i></div>
						</div>

					</div>

				</div>
			</div>
		</div>
	</div>


</div>

{% endblock %}


{% block extra_scripts %}

<script src="{{ STATIC_URL }}css/plugins/Isotope/isotope.pkgd.min.js"></script>
<script src="{{ STATIC_URL }}css/plugins/jquery-ui-1.12.1.custom/jquery-ui.js"></script>
<script src="{{ STATIC_URL }}css/plugins/parallax-js-master/parallax.min.js"></script>
<script src="{{ STATIC_URL }}js/shop_custom.js"></script>

{% endblock %}
</body>