tongoza/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
import certbot_django.server.urls

from tongoza import settings

urlpatterns = [
    path('', include('tongozahome.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('friend/', include('friend.urls')),
    path('users/', include('users.urls')),
    path('marketing/', include('marketing.urls')),
    url(r'^\.well-known/', include(certbot_django.server.urls)),


]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [
        url('__debug__/', include(debug_toolbar.urls))
    ]

tongozahome/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.urls import path

from tongoza import settings
from . import views

app_name = 'tongozahome'

urlpatterns = [

    # path('', views.home, name='home'),

    url(r'^$', views.HomeView.as_view(), name='home'),

    path('profile/<slug>/', views.profileDetail, name='profile'),
    path(r'post/<slug>/', views.PostDetailedView.as_view(), name='postView'),
    path(r'post-create/<pk>/', views.PostCreateView.as_view(), name='post_create'),
    path(r'post/<slug>/update', views.PostUpdateView.as_view(), name='post_update'),
    path(r'post/<slug>/delete', views.PostDeleteView.as_view(), name='post_delete'),

    # path('profile/<slug>', views.profile, name='profile'),
    path('search/', views.search_results, name='search'),


    url(r"^profile-images/(?P<slug>[\w-]+)/$", views.show_profile_images, name="profile_images", ),
    url(r'^profile-images/(?P<slug>[\w-]+)/create$', views.ProfileImageCreateView.as_view(),
        name='profile_image_create'),
    # # url(r'^product-images/(?P<slug>[\w-]+)/create$', views.product_image_create, name='product_image_create'),
    url("^profile-image/(?P<pk>[\w-]+)/update/$", views.ProfileImageUpdateView.as_view(), name="profile_image_update"),
    # url('^profile-image-(?P<pk>[\w-]+)/delete/$', views.ProfileImageDeleteView.as_view(), name="profile_image_delete"),
    url('^profile-image-(?P<pk>[\w-]+)/delete/$', views.delete_image, name="profile_image_delete"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.conf.urls import url
# from django.conf.urls import *
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

from . import views

app_name = 'users'

urlpatterns = [
    url("^profile-(?P<slug>[\w-]+)/update/$", views.profileUpdate, name="profile_update", ),

]

tongozahome/forms.py
from django import forms
from .models import *


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'image', 'caption', 'public']


class PostUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'caption', 'image', 'public']

tongozahome/views.py
import json

from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, UpdateView
from django.contrib.auth.mixins import (LoginRequiredMixin, UserPassesTestMixin)
from django.http import HttpResponseRedirect

from friend.friend_request_status import FriendRequestStatus
from friend.models import FriendList, FriendRequest
from users.forms import UserUpdateForm, ProfileUpdateForm, ProfileUpdateImageForm
from users.profile import set_pic_info, retrieve_profile
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, View, CreateView, UpdateView, DeleteView, FormView, TemplateView
from friend.utils import get_friend_request_or_false
from users.models import User
from .forms import PostForm
from .models import *

import logging

db_logger = logging.getLogger('db')

db_logger.info('info message')
db_logger.warning('warning message')


def home(request):
    return render(request, 'tongozahome/index.html')


class HomeView(ListView):
    model = Profile
    site_name = 'Ongoza'
    template_name = 'tongozahome/index.html'

    # paginate_by = 4

    def get_context_data(self, *, object_list=None, **kwargs):
        super(HomeView, self).get_context_data(**kwargs)

        context = {}

        try:
            active_profiles = Profile.active.all()
            print('active', active_profiles)

            active_posts = Post.objects.filter(active=True)
            print('active_posts', active_posts)

            public_posts = get_public_posts()
            print('public posts', public_posts)

            context['public_posts'] = public_posts

            context.update({
                'profiles': active_profiles,
                'posts': active_posts
            })
        except Exception as e:
            print('e', e)
            db_logger.exception(e)

        return context


@login_required()
def profileDetail(request, slug):
    print('in profile detail')
    context = {}

    viewed_profile = Profile.objects.get(slug=slug)
    print('viewed_profile:', viewed_profile)
    print('one seeing object:', request.user)

    public_posts = get_public_posts()
    print('public posts', public_posts)
    context['public_posts'] = public_posts
    all_posts = get_all_posts()
    context['all_posts'] = all_posts

    try:
        friend_list = FriendList.objects.get(user=viewed_profile.user)
    except FriendList.DoesNotExist:
        friend_list = FriendList(user=viewed_profile.user)
        friend_list.save()

    friends = friend_list.friends.all()
    context['friends'] = friends

    viewed_user_account = viewed_profile.user
    is_self = True
    is_friend = False
    request_sent = FriendRequestStatus.NO_REQUEST_SENT.value
    viewer = request.user
    if viewer != viewed_user_account:
        is_self = False
        if friends.filter(pk=viewer.id):
            is_friend = True
            print(viewer, 'and', viewed_user_account, 'are friends')
        else:
            is_friend = False
            # case 1 check if request has been sent from them to you
            if get_friend_request_or_false(sender=viewed_user_account, receiver=viewer):
                request_sent = FriendRequestStatus.THEM_SENT_TO_YOU.value
                context['pending_friend_request_id'] = get_friend_request_or_false(sender=viewed_user_account,
                                                                                   receiver=viewer).id

            # Case 2 - request has been sent from you to them
            elif get_friend_request_or_false(sender=viewer, receiver=viewed_user_account):
                request_sent = FriendRequestStatus.YOU_SENT_TO_THEM.value

            # No request sent
            else:
                request_sent = FriendRequestStatus.NO_REQUEST_SENT.value
    else:
        # Viewer is looking at their own profile
        print('Viewer is looking at their own profile')
        try:
            friend_requests = FriendRequest.objects.filter(receiver=viewer, is_active=True)
            context['friend_requests'] = friend_requests
        except:
            pass

    # caption = "False"

    # try:
    #     image_shown = viewed_profile.profileimage_set.get(in_display=True, public=True)
    #     print('image_shown:', image_shown.caption)
    #     if image_shown:
    #         if image_shown.caption:
    #             caption = "True"
    # except Exception:
    #     pass
    #
    # caption_json = json.dumps(caption)
    # print('caption is', caption_json)

    context['request_sent'] = request_sent
    context['is_friend'] = is_friend
    context['is_self'] = is_self
    context['object'] = viewed_profile
    # context['caption'] = caption_json

    return render(request, 'tongozahome/profile.html', context)


class ProfileDetailedView(LoginRequiredMixin, DetailView):
    model = Profile
    template_name = 'tongozahome/profile.html'

    def get_context_data(self, **kwargs):
        context = super(ProfileDetailedView, self).get_context_data()
        slug = self.kwargs['slug']
        print(slug)
        print(self.get_object())

        profile = get_object_or_404(Profile, slug=self.kwargs['slug'])
        print('Under view', profile)

        is_self = True
        is_friend = False
        user = self.request.user
        if user.is_authenticated and user != profile.user:
            is_self = False
        elif not user.is_authenticated:
            is_self = False

        # context['is_self'] = is_self
        context['is_friend'] = is_friend
        context['BASE_URL'] = settings.BASE_URL

        return context


@login_required
def likeView(request, slug):
    post = get_object_or_404(Post, id=request.POST.get('post_id'))
    # post.likes.add(request.user)

    liked = False
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
    else:
        post.likes.add(request.user)
        liked = True
    return HttpResponseRedirect(reverse('blog:postView', args=[str(slug)]))


class PostDetailedView(LoginRequiredMixin, DetailView):
    model = Post
    template_name = 'tongozahome/postdetail.html'
    query_pk_and_slug = False

    def get_context_data(self, **kwargs):
        context = super(PostDetailedView, self).get_context_data()

        post = get_object_or_404(Post, slug=self.kwargs['slug'])

        # print("none?", public_posts)
        # print('public posts', public_posts)
        # context['public_posts'] = public_posts
        # all_posts = get_all_posts()
        # context['all_posts'] = all_posts

        liked = False
        if post.likes.filter(id=self.request.user.id).exists():
            liked = True
        context['liked'] = liked

        try:
            friend_list = FriendList.objects.get(user=post.author.user)
        except FriendList.DoesNotExist:
            friend_list = FriendList(user=post.author.user)
            friend_list.save()

        friends = friend_list.friends.all()
        context['friends'] = friends

        viewed_user_account = post.author.user
        is_self = True
        is_friend = False
        request_sent = FriendRequestStatus.NO_REQUEST_SENT.value
        viewer = self.request.user
        if viewer != viewed_user_account:
            is_self = False
            if friends.filter(pk=viewer.id):
                is_friend = True
                print(viewer, 'and', viewed_user_account, 'are friends')
            else:
                is_friend = False
                # case 1 check if request has been sent from them to you
                if get_friend_request_or_false(sender=viewed_user_account, receiver=viewer):
                    request_sent = FriendRequestStatus.THEM_SENT_TO_YOU.value
                    context['pending_friend_request_id'] = get_friend_request_or_false(sender=viewed_user_account,
                                                                                       receiver=viewer).id

                # Case 2 - request has been sent from you to them
                elif get_friend_request_or_false(sender=viewer, receiver=viewed_user_account):
                    request_sent = FriendRequestStatus.YOU_SENT_TO_THEM.value

                # No request sent
                else:
                    request_sent = FriendRequestStatus.NO_REQUEST_SENT.value
        else:
            # Viewer is looking at their own profile
            print('Viewer is looking at their own profile')
            try:
                friend_requests = FriendRequest.objects.filter(receiver=viewer, is_active=True)
                context['friend_requests'] = friend_requests
            except:
                pass

        context['request_sent'] = request_sent
        context['is_friend'] = is_friend
        context['is_self'] = is_self

        return context


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    # fields = ['product', 'title', 'content', 'image']
    template_name = 'tongozahome/modelforms/post_form.html'
    form_class = PostForm

    def get_success_url(self):
        return reverse('tongozahome:postView', kwargs={'slug': self.object.slug})

    def get_context_data(self, **kwargs):
        context = super(PostCreateView, self).get_context_data(**kwargs)

        context.update({

            'page_title': 'Post Create',
        })
        return context

    def form_valid(self, form):
        # form.instance.seller = self.request.user
        obj = form.save(commit=False)
        profile = Profile.objects.get(user=self.request.user)
        obj.author = profile

        obj.save()
        return super(PostCreateView, self).form_valid(form)


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    # fields = ['product', 'title', 'content', 'snippet', 'image']
    form_class = PostForm

tongozahome/templates/tongozahome/base.html
{% load static %}

<!DOCTYPE html PUBLIC "_//W3C//DTD XHTML+RDFa 1.0//EN"
        "http://www.w3.org/MarkUp/DTD/xhtml-rdfa-1.dtd">
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tongoza</title>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-N2C89G38SJ"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-N2C89G38SJ');
    </script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/templatemo-style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons"
      rel="stylesheet">


    <!-- extra head styles -->
    {% block headblock %}

    {% endblock headblock %}
    <!-- extra head styles -->

</head>

<body>
    <div id="loader-wrapper">
        <div id="loader"></div>

        <div class="loader-section section-left"></div>
        <div class="loader-section section-right"></div>

    </div>
   <div class="pt-0 ms">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} " role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
        {% endif %}
    </div>

    {% block navbar %}
      {% include 'tongozahome/snippets/navbar.html' %}
    {% endblock %}

    {% block search %}
        <div class="tm-hero d-flex justify-content-center align-items-center" data-parallax="scroll" data-image-src="{% static 'img/potential1.jpg' %}">
            <form class="d-flex tm-search-form" onsubmit="executeQuery();">
                <input class="form-control tm-search-input" type="search" name="q" placeholder="Search for Buddies" aria-label="Search" id="id_q">
                <button class="btn btn-outline-success tm-search-btn" type="submit">
                    <i class="fas fa-search"></i>
                </button>
            </form>
        </div>
    {% endblock %}

    <!-- site wrapper-->
    {% block site_wrapper %}

    {% endblock %}
    <!-- site wrapper-->

    {% block footer %}
       {% include 'tongozahome/snippets/footer.html' %}
    {% endblock %}

    <script src="{% static 'js/plugins.js' %}"></script>

    <script>
        $(window).on("load", function() {
            $('body').addClass('loaded');
        });
    </script>

    <script type="text/javascript">
        function executeQuery(){
            var query = document.getElementById("id_q").value;

            window.location.replace("{% url 'tongozahome:search' %}?q=" + query);

        }
    </script>

        <script type="text/javascript">

        // called from base_js.html

        function onFriendRemoved(){
            location.reload();
        }

        function onFriendRequestAccepted(){
            location.reload();
        }

        function onFriendRequestDeclined(){
            location.reload();
        }


        function triggerAcceptFriendRequest(friend_request_id){
            acceptFriendRequest(friend_request_id, onFriendRequestAccepted)
        }

        function triggerDeclineFriendRequest(friend_request_id){
            declineFriendRequest(friend_request_id, onFriendRequestDeclined)
        }

    </script>
    <script type="text/javascript">
        $('.alert').alert()
        $(".alert").alert('close')
    </script>

    {% include 'friend/snippets/accept_friend_request.html' %}
    {% include 'friend/snippets/decline_friend_request.html' %}

    {#% include 'chat/create_or_return_private_chat.html' %#}

    <!-- extra scritpts-->
    {% block extra_scripts %}

    {% endblock extra_scripts %}
    <!-- extra scritpts-->


</body>

</html>

tongozahome/templates/tongozahome/index.html
{% extends 'tongozahome/base.html' %}
{% load static %}

{% block headblock %}

{% endblock headblock %}
{% block site_wrapper %}
<main>
    <div class="container-fluid tm-container-content tm-mt-60">
        <div class="row mb-2">
            <h2 class="col-6 tm-text-primary">
               New Profiles
            </h2>
            <div class="col-6 d-flex justify-content-end align-items-center">
                <form action="" class="tm-text-primary">
                    Page <input type="text" value="1" size="1" class="tm-input-paging tm-text-primary"> 1
                </form>
            </div>
        </div>
        <div class="row tm-gallery">
            {% for profile in profiles %}
                {% if profile.profileimage_set.all %}
                    {% for image in profile.profileimage_set.all %}
                        {% if image.in_display %}
                            <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6 col-12 mb-5">

                                <figure class="effect-ming tm-video-item">
                                    <img src="{{ image.image.medium.url }}" alt="{{ profile }}" class="img-fluid">
                                    <figcaption class="d-flex align-items-center justify-content-center">
                                        <h2>Meet {{ profile.user }}</h2>
                                        <a href="{{ profile.get_absolute_url }}">View more</a>
                                    </figcaption>
                                </figure>

                                {% if profile.country %}
                                <div class="d-flex justify-content-between tm-text-gray">
                                    <span class="tm-text-gray-dark">{{profile.city}}</span>
                                    <span>{{ profile.country }}</span>
                                </div>
                                {% endif %}
                            </div>
                        {% endif %}
                    {% endfor %}
                {% endif %}
            {% endfor %}
        </div> <!-- row -->

        <div class="row mb-2">
            <h2 class="col-6 tm-text-primary">
                Recent Posts
            </h2>
<!--            <div class="col-6 d-flex justify-content-end align-items-center">-->
<!--                <form action="" class="tm-text-primary">-->
<!--                    Page <input type="text" value="1" size="1" class="tm-input-paging tm-text-primary"> 1-->
<!--                </form>-->
<!--            </div>-->
        </div>
        <div class="row tm-mb-90 tm-gallery">
            {% for post in public_posts %}

                <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6 col-12 mb-5">

                    <figure class="effect-ming tm-video-item">
                        <img src="{{ post.image.medium.url }}" alt="{{ post.author }}" class="img-fluid">
                        <figcaption class="d-flex align-items-center justify-content-center">
                            <h2>From {{ post.author }}</h2>
                            <a href="{% url 'tongozahome:postView' post.slug %}">View more</a>
                        </figcaption>
                    </figure>

                    <div class="d-flex justify-content-between tm-text-gray">
                        <span class="tm-text-gray-dark">{{ post.title }}</span>
                        <span>{{ post.created.date }}</span>
                    </div>
                </div>

            {% endfor %}
        </div> <!-- row -->

        <div class="row tm-mb-90">
            <div class="col-12 d-flex justify-content-between align-items-center tm-paging-col">
                <a href="javascript:void(0);" class="btn btn-primary tm-btn-prev mb-2 disabled">Previous</a>
                <div class="tm-paging d-flex">
                    <a href="javascript:void(0);" class="active tm-paging-link">1</a>
<!--                    <a href="javascript:void(0);" class="disabled tm-paging-link">2</a>-->
<!--                    <a href="javascript:void(0);" class="disabled tm-paging-link">3</a>-->
<!--                    <a href="javascript:void(0);" class="disabled tm-paging-link">4</a>-->
                </div>
                <a href="javascript:void(0);" class="disabled btn btn-primary tm-btn-next">Next Page</a>
            </div>
        </div>
    </div> <!-- container-fluid, tm-container-content -->
</main>

{% endblock site_wrapper %}

tongozahome/templates/tongozahome/search_results.html
{% extends 'tongozahome/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block extra_head %}
    <title>Search Results</title>
    <style type="text/css">
	.profile-image{
		max-height: 100px;
		max-width: 100px;
	}
	.profile-image{
		border-radius: 12px;
	}
	.card{
		border-radius: 12px;
	}
	.friends-text{
		color: #000;
		font-weight: 500;
	}
	.friends-text-container{
		border: 1px solid #cccccc;
		border-radius: 12px;
	}
	.friends-btn:hover {
		background-color: #bfbfbf;
		border-color: #bfbfbf;
	}
	.dropdown-toggle::after {
		content: none;
	}
	.profile-link{
		color: #000;
	}
	.checkmark-icon{
		color: green;
	}
	.cancel-icon{
		color: red;
	}
</style>


{% endblock %}

{% block site_wrapper %}
<div class="container">
	<div class="card p-2">

		{% if accounts %}
		<div class="d-flex flex-row flex-wrap">
		{% for account in accounts %}
		<div class="card flex-row flex-grow-1 p-2 mx-2 my-2 align-items-center">
			<a class="profile-link" href="{% url 'account:view' user_id=account.0.id %}">
				<div class="card-image m-2">
					<img class="img-fluid profile-image" src="{{account.0.profile_image.url}}" alt="">
				</div>
			</a>
			<a class="profile-link" href="{% url 'account:view' user_id=account.0.id %}">
				<div class="card-center px-2">
					<h4 class="card-title">{{account.0.username}}</h4>
					{% if account.1 %}
					<p class="card-text"><a href="#" onclick="createOrReturnPrivateChat('{{account.0.id}}')">Send a Message</a></p>
					{% endif %}

				</div>
			</a>
			<div class="d-flex flex-row card-right flex-grow-1 justify-content-end mx-2">
				{% if account.1 %}
					<div class="d-flex flex-row friends-text-container p-3">
						<p class="friends-text m-auto">
							Friends
						</p>
						<span class="material-icons checkmark-icon m-auto pl-2">
						check_circle_outline
						</span>
					</div>
				{% else %}
					{% if account.0 !=  request.user %}
						<div class="d-flex flex-row friends-text-container p-3">
							<p class="friends-text m-auto">
								Not Friends
							</p>
							<span class="material-icons cancel-icon m-auto pl-2">cancel</span>
						</div>
					{% endif %}
				{% endif %}
				{% if account.0 == request.user %}
					<div class="d-flex flex-row friends-text-container p-3">
						<p class="friends-text m-auto">
							This is you
						</p>
						<span class="material-icons m-auto pl-2">
						person_pin
						</span>
					</div>
				{% endif %}
			</div>
		</div>
		{% if forloop.counter|divisibleby:2 %}
		</div><div class="d-flex flex-row flex-wrap">
		{% endif %}

		{% endfor %}

		{% else %} <!-- If no friends -->
		<div class="d-flex flex-row flex-grow-1 justify-content-center align-items-center p-4">
			<p>No results</p>
		</div>
		{% endif %}
		</div>
	</div>

</div>

{% endblock site_wrapper %}

{% block extra_scripts %}

{% endblock extra_scripts %}