friend/urls.py
from django.urls import path
from friend.views import (
    send_friend_request,
    view_friend_requests,
    accept_friend_request,
    view_friends,
    remove_friend,
    decline_friend_request,
    cancel_friend_request,
)


app_name = 'friend'

urlpatterns = [
    path('accept_friend_request/<friend_request_id>/', accept_friend_request, name='accept_friend_request'),
    path('decline_friend_request/<friend_request_id>/', decline_friend_request, name='decline_friend_request'),
    path('friend_remove/', remove_friend, name='remove_friend'),
    path('friend_request/', send_friend_request, name='friend_request'),
    path('friend_request_cancel/', cancel_friend_request, name='friend_request_cancel'),
    path('friend_request/<slug>/', view_friend_requests, name='view_requests'),
    path('friends_list/<slug>/', view_friends, name='view_friends'),
]

tongoza/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
import certbot_django.server.urls

from tongoza import settings

urlpatterns = [
    path('', include('tongozahome.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('friend/', include('friend.urls')),
    path('users/', include('users.urls')),
    path('marketing/', include('marketing.urls')),
    url(r'^\.well-known/', include(certbot_django.server.urls)),


]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [
        url('__debug__/', include(debug_toolbar.urls))
    ]

tongozahome/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.urls import path

from tongoza import settings
from . import views

app_name = 'tongozahome'

urlpatterns = [

    # path('', views.home, name='home'),

    url(r'^$', views.HomeView.as_view(), name='home'),

    path('profile/<slug>/', views.profileDetail, name='profile'),
    path(r'post/<slug>/', views.PostDetailedView.as_view(), name='postView'),
    path(r'post-create/<pk>/', views.PostCreateView.as_view(), name='post_create'),
    path(r'post/<slug>/update', views.PostUpdateView.as_view(), name='post_update'),
    path(r'post/<slug>/delete', views.PostDeleteView.as_view(), name='post_delete'),

    # path('profile/<slug>', views.profile, name='profile'),
    path('search/', views.search_results, name='search'),


    url(r"^profile-images/(?P<slug>[\w-]+)/$", views.show_profile_images, name="profile_images", ),
    url(r'^profile-images/(?P<slug>[\w-]+)/create$', views.ProfileImageCreateView.as_view(),
        name='profile_image_create'),
    # # url(r'^product-images/(?P<slug>[\w-]+)/create$', views.product_image_create, name='product_image_create'),
    url("^profile-image/(?P<pk>[\w-]+)/update/$", views.ProfileImageUpdateView.as_view(), name="profile_image_update"),
    # url('^profile-image-(?P<pk>[\w-]+)/delete/$', views.ProfileImageDeleteView.as_view(), name="profile_image_delete"),
    url('^profile-image-(?P<pk>[\w-]+)/delete/$', views.delete_image, name="profile_image_delete"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.conf.urls import url
# from django.conf.urls import *
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

from . import views

app_name = 'users'

urlpatterns = [
    url("^profile-(?P<slug>[\w-]+)/update/$", views.profileUpdate, name="profile_update", ),

]

tongozahome/models.py
import itertools
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.text import slugify
from stdimage import StdImageField
from django_countries.fields import CountryField
from ckeditor.fields import RichTextField
from utils.models import CreationModificationDateMixin
from phonenumber_field.modelfields import PhoneNumberField
from mptt.models import MPTTModel, TreeForeignKey

# Create your models here.
from tongoza import settings


class ActiveProfileManager(models.Manager):
    def all(self):
        return super(ActiveProfileManager, self).all().filter(is_active=True)


class ProfileManager(models.Manager):
    def get_by_natural_key(self, slug):
        return self.get(slug=slug)


class AbstractProfile(CreationModificationDateMixin):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True, default='', max_length=255, editable=False)
    aboutMe = models.CharField(max_length=400)
    company = models.CharField(max_length=100, blank=True, null=True)
    role = models.CharField(max_length=100, blank=True, null=True)
    education_institution = models.CharField(max_length=200, blank=True, null=True)
    course = models.CharField(max_length=200, blank=True, null=True)
    address = models.CharField(max_length=60, blank=True, null=True)
    linkedin = models.CharField(max_length=150, blank=True, null=True)
    facebook = models.CharField(max_length=150, blank=True, null=True)
    twitter = models.CharField(max_length=150, blank=True, null=True)
    telegram_username = models.CharField(max_length=60, blank=True, null=True)
    snapchat_username = models.CharField(max_length=60, blank=True, null=True)
    messenger = models.CharField(max_length=60, blank=True, null=True)
    whatsapp_phone_number = PhoneNumberField(blank=True, null=True)
    country = CountryField(multiple=False, blank=True, null=True)
    city = models.CharField(max_length=60, blank=True, null=True)
    gender = models.CharField(max_length=1, blank=True, null=True)
    postal_code = models.CharField(max_length=10, blank=True, null=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        abstract = True


class Profile(AbstractProfile):
    government_issued_id = StdImageField(upload_to='tongoza/images/national_identificantions/', blank=True, null=True,
                                         help_text='Required only if you wish to have a dual'
                                                   ' profile for both Tongoza light mode and Tongoza darke mode')

    active = ActiveProfileManager()
    objects = ProfileManager()

    class Meta(AbstractProfile.Meta):
        db_table = 'Light Mode Profile'

    def __str__(self):
        return str(self.user.username)

    def natural_key(self):
        return (self.slug,)

    def get_absolute_url(self):
        return reverse('tongozahome:profile', kwargs={'slug': self.slug})

    def get_image_in_display(self):
        image = self.profileimage_set.filter(in_display=True, dark_mode_pic=False, public=True)
        if image:
            return image[0]

    def get_caption(self):
        image = self.get_image_in_display()
        if image:
            if image.caption:
                return image.caption

    def get_profile_pic(self):
        image = self.profileimage_set.filter(profile_pic=True, dark_mode_pic=False)
        if image:
            return image[0]
        else:
            return self.get_image_in_display()

    def get_dark_profile_pic(self):
        image = self.profileimage_set.filter(profile_pic=True, dark_mode_pic=True)
        if image:
            return image[0]
        else:
            return self.get_image_in_display()

    def get_light_mode_public_images(self):
        images = self.profileimage_set.filter(in_display=False, dark_mode_pic=False, public=True)
        return images

    def get_light_mode_images(self):
        images = self.profileimage_set.filter(in_display=False, dark_mode_pic=False)
        return images

    def get_user_public_posts(self):
        posts = self.post_set.filter(active=True, public=True)
        return posts

    def get_user_all_posts(self):
        posts = self.post_set.filter(active=True)
        return posts

    def _generate_slug(self):
        value = self.user.username
        slug_original = slugify(value, allow_unicode=True)

        slug_candidate = '{}'.format(slug_original)

        return slug_candidate

    def save(self, *args, **kwargs):
        if not self.pk or self.slug != self.user.username:
            print('came to update sluggg')
            self.slug = self._generate_slug()
        if self.get_image_in_display():
            self.is_active = True
        else:
            self.is_active = False

        super().save(*args, **kwargs)


class DisplayImageManager(models.Manager):
    def get_query_set(self):
        return super(DisplayImageManager, self).get_query_set().filter(in_display=True)


class ProfileImage(CreationModificationDateMixin):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    image = StdImageField(upload_to='tongoza/images/profile_images', variations={
        'thumbnail': (250, 250),
        'medium': (420, 236, True),
        'large': (800, 675)
    }, delete_orphans=True)
    caption = models.TextField(blank=True, null=True,
                               help_text="Write something about the moment captured in this image")
    public = models.BooleanField(default=True)
    in_display = models.BooleanField(default=True)
    profile_pic = models.BooleanField(default=True)

    dark_mode_pic = models.BooleanField(default=False)
    displayed = DisplayImageManager()
    objects = models.Manager()

    class Meta:
        ordering = ('-in_display',)

    def __str__(self):
        return str(self.profile)

    def save(self, *args, **kwargs):
        if self.in_display:
            self.profile.active = True
            self.profile.save()

        super().save(*args, **kwargs)


def get_public_posts():
    posts = Post.objects.filter(active=True, public=True)
    return posts


def get_all_posts():
    posts = Post.objects.filter(active=True)
    return posts


class Post(CreationModificationDateMixin):
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    # author = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True)
    slug = models.SlugField(unique=True,
                            default='',
                            editable=False,
                            max_length=255,
                            )
    title = models.CharField(max_length=100)
    image = StdImageField(upload_to='tongoza/posts/images/products',
                          help_text="upload post cover Image",
                          variations={
                              'thumbnail': (250, 250),
                              'medium': (420, 236, True),
                              'large': (800, 675)
                          }, delete_orphans=True)
    caption = models.TextField(help_text="Inspire your audience with the moment captured in this image")
    public = models.BooleanField(default=True, help_text="Everyone can see this post.")

    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='post_likes')
    active = models.BooleanField(default=True)

    def __str__(self):
        return str(self.title)

    def get_total_likes(self):
        return self.likes.count()

    def get_user_all_other_posts(self):
        posts = Post.objects.filter(active=True).exclude(id=self.id)
        return posts

    def get_user_other_public_posts(self):
        posts = Post.objects.filter(active=True, public=True).exclude(id=self.id)
        return posts

    def cross_reads(self):
        # orders = Order.objects.filter(items__item=self)
        # order_items = OrderItem.objects.filter(order__in=orders).exclude(item=self)
        posts = Post.objects.all().exclude(slug=self.slug)
        return posts

    def get_absolute_url(self):

        return reverse('tongozahome:postView', kwargs={'slug': self.slug})

    def _generate_slug(self):
        max_length = self._meta.get_field('slug').max_length
        value = self.title
        slug_candidate = slug_original = slugify(value, allow_unicode=True)
        for i in itertools.count(1):
            if not Post.objects.filter(slug=slug_candidate).exists():
                break
            slug_candidate = '{}-{}'.format(slug_original, i)

        return slug_candidate

    def save(self, *args, **kwargs):
        if not self.pk:
            self.slug = self._generate_slug()

        super().save(*args, **kwargs)


class Comments(MPTTModel):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments', null=True, blank=True)
    parent = TreeForeignKey('self', on_delete=models.CASCADE,
                            null=True, blank=True, related_name='children')
    content = models.TextField()
    publish = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=True)

    class MPTTMeta:
        order_insertion_by = ('publish',)

    def __str__(self):
        return f'Comment by {self.post.author}'

users/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from datetime import date
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.validators import UnicodeUsernameValidator
from phonenumber_field.modelfields import PhoneNumberField


# Create your models here.
class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, username, password, **extra_fields):
        if not email:
            raise ValueError("Users must have an email address")
        if not username:
            raise ValueError('Users must have a username')
        email = self.normalize_email(email)
        user = self.model(email=email, username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, username, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, username, password, **extra_fields)

    def create_superuser(self, email, username, password, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True")
        return self._create_user(email, username, password, **extra_fields)


class LowercaseCharField(models.CharField):
    """
    Override CharField to convert to lowercase before saving.
    """

    def to_python(self, value):
        """
        Convert text to lowercase.
        """
        value = super(LowercaseCharField, self).to_python(value)
        # Value can be None so check that it's a string before lowercasing.
        if isinstance(value, str):
            return value.lower()
        return value


class User(AbstractUser):
    username = LowercaseCharField(
        # Copying this from AbstractUser code
        _('username'),
        max_length=150,
        unique=True,
        help_text=_('Required. Letters, digits and @/./+/-/_ only.'),
        validators=[UnicodeUsernameValidator(), ],
        error_messages={
            'unique': _("A user with that dark Mode username already exists."),
        },
    )
    dark_mode_username = LowercaseCharField(
        # Copying this from AbstractUser code
        _('dark_mode_username'),
        max_length=150,
        unique=True,
        blank=True,
        null=True,
        help_text=_('Required. Letters, digits and @/./+/-/_ only.'),
        validators=[UnicodeUsernameValidator(), ],
        error_messages={
            'unique': _("A user with that dark Mode username already exists."),
        },
    )
    email = models.EmailField(max_length=255, unique=True)
    phone = PhoneNumberField(blank=True, null=True)
    allow_direct_calls = models.BooleanField(default=True)
    dob = models.DateField(max_length=8, blank=True, null=True)

    USERNAME_FIELD = 'email'

    REQUIRED_FIELDS = ['username', ]

    objects = UserManager()

    def __str__(self):
        return str(self.username, )

    def get_absolute_url(self):
        return "/users/%i/" % self.pk

    def get_email(self):
        return self.email

    def has_module_perms(self, app_label):
        return True

    def calculate_age(self):
        if self.dob:
            today = date.today()
            return today.year - self.dob.year - ((today.month, today.day) < (self.dob.month, self.dob.day))

    def get_last_login(self):
        last = self.last_login

tongozahome/forms.py
from django import forms
from .models import *


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'image', 'caption', 'public']


class PostUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'caption', 'image', 'public']

tongozahome/templates/tongozahome/snippets/logo.html
<a class="navbar-brand" href="{% url 'tongozahome:home' %}"><img class="img-fluid mx-auto d-block" src="https://images.cooltext.com/5548960.png" width="310" height="65" alt="Tongoza - To Lead" /></a>

tongozahome/templates/tongozahome/snippets/navbar.html
{% load static %}
{% load notification_tags %}
 <nav class="navbar navbar-expand-lg">
    <div class="container-fluid">
            {% include 'tongozahome/snippets/logo.html' %}
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <a class="nav-link nav-link-1 active" aria-current="page" href="{% url 'tongozahome:home' %}">Posts</a>
            </li>
<!--              <li class="disabled nav-item">-->
<!--                <a class="nav-link nav-link-1 active" aria-current="page" href="#">Videos</a>-->
<!--            </li>-->
               {% if request.user.is_authenticated %}
                <li class="nav-item">
                    {% if request|friend_request_count %}
                    <a class="nav-link nav-link-3" href="{% url 'friend:view_requests' user_profile.slug %}"><span class="material-icons" style="color: #A1030F">
                    person_add</span>
                    <span style="color: #00970B">{{ request|friend_request_count }}</span></a>
                    {% else %}
                     <a class="nav-link nav-link-3" href="{% url 'friend:view_requests' user_profile.slug %}"><span class="material-icons">
                    person_add</span></a>
                    {% endif %}
                </li>
                <li class="nav-item">
                    <a class="disabled nav-link nav-link-3" href="#"><span class="material-icons">chat</span></a>
                </li>
                <li class="nav-item">
                    <a class="disabled nav-link nav-link-2" href="#"><span class="material-icons">notifications</span></a>
                </li>
                <li class="nav-item">
                    <div class="btn-group dropleft">
                        <img class="account-image rounded-circle m-auto d-block dropdown-toggle" id="id_profile_links"
                             data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="object-fit: cover"
                             src="{% if not user_profile.get_profile_pic %} {% static 'img/dummy_image.png'%} {% else %}
                             {{ user_profile.get_profile_pic.image.thumbnail.url }} {% endif %}" alt="{{request.user.username}}" width="40" height="40">
                        <div class="dropdown-menu" aria-labelledby="id_profile_links">
                            {% if user_profile.slug %}
                            <a class="dropdown-item" href="{% url 'users:profile_update' user_profile.slug %}">My Account</a>
                            <a class="dropdown-item" href="{{ user_profile.get_absolute_url}}">My Profile</a>
                            {% endif %}
                            <a class="dropdown-item" href="{% url 'account_logout' %}">Logout</a>
                        </div>
                    </div>
                </li>

                {% else %}
                <li class="nav-item">
                    <a class="nav-link nav-link-4" href="{% url 'account_signup' %}?next={{ request.path }}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link nav-link-5" href="{% url 'account_login' %}?next={{ request.path }}">Sign In</a>
                </li>
                {% endif %}


        </ul>
        </div>
    </div>
</nav>

tongozahome/templates/tongozahome/snippets/post_detail_usercard.html
{% load static %}
{% block headblock %}

{% endblock %}
<div class="card card-profile shadow">
    <div class="row justify-content-center">
      <div class="col-lg-3 order-lg-2" >
        <div class="card-profile-image">
          <a href="{{ object.author.get_absolute_url }}">
            <img src="{% if not object.author.get_profile_pic %} {% static 'img/dummy_image.png'%} {% else %}{{ object.author.get_profile_pic.image.thumbnail.url }} {% endif %}" class="rounded-circle" width="160" height="160" style="object-fit:cover">
          </a>
        </div>
      </div>
    </div>
    <div class="card-header text-center border-0 pt-8 pt-md-4 pb-0 pb-md-4">
      <div class="row">
        <div class="d-flex justify-content-between">
            {% if is_self %}
              <a href="{% url 'users:profile_update' object.author.slug %}" class="btn btn-sm btn-info mr-4">My Account</a>
              <a href="{% url 'tongozahome:profile_images' object.author.slug %}" class="btn btn-sm btn-secondary float-right">Update Photos</a>
            {% else %}
                {% if not is_friend %}
                    {% if request_sent == -1 %}
                        {% if user_profile.get_profile_pic and user_profile.gender %}
                          <a href="#" class="btn btn-sm btn-info mr-4" id="id_send_friend_request_btn">Connect</a>
                        {% else %}
                        <a href="#" class="btn btn-sm btn-info no-match mr-4">Connect</a>
                        {% endif %}
                      <!--No request sent-->
                    {% endif %}
                    {% if request_sent == 1 %}
                      <!--You sent them a friend request-->
                      <a href="#" class="btn btn-sm btn-info mr-4" id="id_cancel_friend_request_btn" style="background-color: #A1030F">Cancel Request</a>
                    {% endif %}
                {% else %}
                <!--Is already your friend-->
                  <div class="dropdown">
                    <button class="btn btn-sm btn-info mr-4 dropdown-toggle friends-btn" type="button" id="id_friends_toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="background-color: #198754">
                    Your Buddy
                    </button>
                    <div class="dropdown-menu btn-sm" aria-labelledby="id_friends_toggle">
                        <a href="#" class="btn btn-sm btn-info mr-4" id="id_unfriend_btn" style="background-color: #A1030F">UnBuddy</a>
                    </div>
                  </div>
              {% endif %}
             {% if request_sent == 0 %}
                     {% if user_profile.get_profile_pic and user_profile.gender %}
                        <a id="id_confirm_{{ object.author.user.id }}" href="#" class="btn btn-sm btn-info mr-4" onclick='triggerAcceptFriendRequest("{{pending_friend_request_id}}")' style="background-color: #198754">Accept Request</a>
                        <a id="id_cancel_{{ object.author.user.id }}" href="#" class="btn btn-sm btn-info mr-4" onclick='triggerDeclineFriendRequest("{{pending_friend_request_id}}")' style="background-color: #A1030F">Decline</a>

                    {% else %}
                        <a href="#" class="btn btn-sm btn-info mr-4 no-accept"  style="background-color: #198754">Accept Request</a>
                        <a href="#" class="btn btn-sm btn-info mr-4 no-accept"  style="background-color: #A1030F">Decline</a>
                    {% endif %}
                {% else %}
                    <a href="#" class="btn btn-sm btn-secondary float-right">Hangout</a>
                {% endif %}
            {% endif %}
        </div>
      </div>
    </div>
    <div class="card-body pt-0 pt-md-4">
      <div class="row">
        {% if is_friend or is_self %}
            {% if object.author.user.phone and object.author.user.allow_direct_calls %}
                <div class="col-xl-12" style="margin: auto">
                    <div class="d-flex flex-row justify-content-center m-2 px-4 mt-md-4" onclick="createOrReturnPrivateChat('{{id}}')">
                        <a class="btn btn-primary" href='tel:{{object.user.phone}}'>
                            <span class="message-btn-text m-auto pl-2"><i class="fa fa-phone"></i> Call Me</span>
                        </a>
                    </div>
                </div>
            {% else %}
            <div class="col-xl-12" style="margin: auto">
                <div class="d-flex flex-row justify-content-center m-2 px-4 mt-md-4" onclick="createOrReturnPrivateChat('{{id}}')">
                    <a class="disabled btn btn-primary" href='tel:{{object.user.phone}}'>
                        <span class="message-btn-text m-auto pl-2"><i class="fa fa-phone"></i> Call Me</span>
                    </a>
                </div>
            </div>
            {% endif %}
            <div class="col-xl-12">
                     <div class="d-flex flex-row justify-content-between m-2 px-4 mt-md-4" style="margin: auto">
                       <ul class="social-network social-circle">

                        {% if object.author.whatsapp_phone_number %}
                            <li><a target="_blank" href="https://wa.me/{{object.whatsapp_phone_number}}?text=Hello! It's {{object.user.username|capfirst}} from Tongaza. Glad we're friends" class="icoWhatsapp" title="Whatsapp"><i class="fa fa-whatsapp"></i></a></li>
                        {% endif %}
                        {% if object.author.telegram_username %}
                           <li><a target="_blank" href="https://telegram.me/{{ object.telegram_username }}" class="icoTelegram" title="Telegram"><i class="fa fa-telegram"></i></a></li>
                        {% endif %}
                        {% if object.author.snapchat_username %}
                           <li><a target="_blank" href="https://msng.link/o/?{{object.snapchat_username}}=sc" class="icoSnapchat" title="Snapchat"><i class="fa fa-snapchat-ghost"></i></a></li>
                        {% endif %}
                        {% if object.author.messenger %}
                            <li><a target="_blank" href="https://www.messenger.com/t/{{ object.messenger }}" class="icoMessenger" title="Messenger"><i class="fab fa-facebook-messenger"></i></a></li>
                        {% endif %}
                        {% if object.author.user.phone and object.user.allow_direct_calls %}
                            <li><a target="_blank" href="tel:{{object.user.phone}}" class="icoCall" title="Call"><i class="fa fa-phone"></i></a></li>
                        {% endif %}
                       </ul>

                     </div>
                </div>
        {% endif %}
        {% if is_self and friend_requests %}
        <div class="col-xl-8" style="margin: auto">
           <div class="d-flex flex-column align-items-center m-2 px-4 mt-md-2">
                <a href="{% url 'friend:view_requests' object.author.slug %}" class="d-flex flex-row align-items-center btn btn-primary m-2 px-4 mt-md-4"><span class="material-icons mr-2 person-add-icon">person_add</span>Friend Requests({{friend_requests|length}})</a>
          </div>
        </div>
        {% endif %}

        <div class="col">
          <div class="card-profile-stats d-flex justify-content-center mt-md-2">
            <div>
                {% if is_friend or is_self %}
                    <a href="{% url 'friend:view_friends' object.author.slug %}">
                {% endif %}
                  <span class="heading">{{ friends|length }}</span>
                  <span class="description"><span class="material-icons mr-2">
                  people
                  </span>Buddies</span>
                </a>
            </div>
            <div>
                {% if is_self %}
                    <a href="{% url 'tongozahome:profile_images' object.author.slug %}">
                {% endif %}
                    <span class="heading">{{ object.profileimage_set.all|length }}</span>

                    <span class="description"><span class="material-icons mr-2">
                    collections
                    </span>Photos</span>
                </a>
              </div>
<!--            <div>-->
<!--              <span class="heading">89</span>-->
<!--              <span class="description"><span class="material-icons mr-2">-->
<!--              comment-->
<!--              </span>Comments</span>-->
<!--            </div>-->
          </div>
        </div>
      </div>
      <div class="text-center">
        {% if object.author.user.dob %}
        <h3>
            {{ object.author|capfirst }}<span class="font-weight-light">, {{ object.author.user.calculate_age }} </span>
        </h3>
        {% else %}
         <h3>
            {{ object.author|capfirst }}
        </h3>
        {% endif %}

        {% if object.country %}
        <div class="h5 font-weight-300">
          <i class="ni location_pin mr-2"></i>{{ object.author.country }}, {{ object.author.city }}
        </div>
        {% endif %}
        <div class="h5 font-weight-300">
          {% if object.author.gender %}
            {% if gender == 'F' %}
            <span class="material-icons">female</span>
            {% else %}
            <span class="material-icons">male</span>
            {% endif %}
          {% else %}
          <span class="material-icons">transgender</span>
          {% endif %}

        </div>
        <div class="h5 ni education_hat mr-2">
          Last login - {{ object.author.user.last_login.date }}
        </div>
          {% if object.author.company and object.author.role %}
            <div class="h5 mt-4">
                  <i class="ni business_briefcase-24 mr-2"></i>{{object.author.role}} - {{object.author.company}}
                </div>
          {% endif %}

          {% if object.author.education_institution and object.course %}
          <div>
            <i class="ni education_hat mr-2"></i> {{ object.author.education_institution }} - {{ object.author.course }}
          </div>
          {% endif %}

        <hr class="my-4">
        <p>{{object.author.aboutMe|safe}}</p>
      </div>
    </div>
  </div>

{% block extra_scripts %}
<script type="text/javascript">
    $(document).ready(function() {
      $('.no-match').click(function() {
       alert("Update your Profile picture and your Account information to send a Buddy request")
      });
      $('.no-accept').click(function() {
       alert("Update your Profile picture and your Account information to accept/decline a Buddy request")
      });
    });
</script>
{% endblock %}