friend/urls.py
from django.urls import path
from friend.views import (
    send_friend_request,
    view_friend_requests,
    accept_friend_request,
    view_friends,
    remove_friend,
    decline_friend_request,
    cancel_friend_request,
)


app_name = 'friend'

urlpatterns = [
    path('accept_friend_request/<friend_request_id>/', accept_friend_request, name='accept_friend_request'),
    path('decline_friend_request/<friend_request_id>/', decline_friend_request, name='decline_friend_request'),
    path('friend_remove/', remove_friend, name='remove_friend'),
    path('friend_request/', send_friend_request, name='friend_request'),
    path('friend_request_cancel/', cancel_friend_request, name='friend_request_cancel'),
    path('friend_request/<slug>/', view_friend_requests, name='view_requests'),
    path('friends_list/<slug>/', view_friends, name='view_friends'),
]

tongoza/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
import certbot_django.server.urls

from tongoza import settings

urlpatterns = [
    path('', include('tongozahome.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('friend/', include('friend.urls')),
    path('users/', include('users.urls')),
    path('marketing/', include('marketing.urls')),
    url(r'^\.well-known/', include(certbot_django.server.urls)),


]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [
        url('__debug__/', include(debug_toolbar.urls))
    ]

users/urls.py
from django.conf.urls import url
# from django.conf.urls import *
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

from . import views

app_name = 'users'

urlpatterns = [
    url("^profile-(?P<slug>[\w-]+)/update/$", views.profileUpdate, name="profile_update", ),

]

friend/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from utils.models import CreationModificationDateMixin


# Create your models here.

class FriendList(CreationModificationDateMixin):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="user")
    friends = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='friends')

    def __str__(self):
        return self.user.username

    def add_friend(self, account):
        if not account in self.friends.all():
            self.friends.add(account)

    def remove_friend(self, account):
        if account in self.friends.all():
            self.friends.remove(account)

    def unfriend(self, removee):
        # initiate the action of unfriending
        remover_friends_list = self

        # Remove friend from remover friend list
        remover_friends_list.remove_friend(removee)

        # remove friend from removee friend list
        friends_list = FriendList.objects.get(user=removee)
        friends_list.remove_friend(self.user)
        friends_list.save()

    def is_mutual_friend(self, friend):
        if friend in self.friends.all():
            return True
        return False


class FriendRequest(CreationModificationDateMixin):
    # sender - a person who initiates the friend request
    # receiver - a person receiving the friend request

    sender = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='receiver')
    is_active = models.BooleanField(blank=True, null=False, default=True)

    def __str__(self):
        return '{}-{}'.format(self.sender, self.receiver)

    def accept(self):
        """
        update request on sender and receiver
        """

        receiver_friend_list = FriendList.objects.get(user=self.receiver)
        if receiver_friend_list:
            receiver_friend_list.add_friend(self.sender)
            receiver_friend_list.save()

        sender_friend_list = FriendList.objects.get(user=self.sender)
        if sender_friend_list:
            sender_friend_list.add_friend(self.receiver)
            self.is_active = False
            self.save()

    def decline(self):
        """
        Decline friend request
        set is active to false
        from receiver
        """

        self.is_active = False
        self.save()

    def cancel(self):
        """
        from the sender
        """
        self.is_active = False
        self.save()

friend/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
import json

from friend.utils import get_friend_request_or_false
from tongozahome.models import Profile
from users.models import User
from friend.models import FriendRequest, FriendList
from django.contrib.auth.decorators import login_required


@login_required
def send_friend_request(request):
    sender = request.user
    print('sender_id', sender.id)
    payload = {}
    message = 'Friend request sent.'
    payload['message'] = message

    if request.method == 'POST':
        viewed_user_id = request.POST.get('receiver_user_id')
        print("viewed_user_id", viewed_user_id)
        if viewed_user_id:
            receiver = User.objects.get(pk=viewed_user_id)
            try:
                friend_requests = FriendRequest.objects.filter(sender=sender, receiver=receiver)

                # find out if request is active
                try:
                    for request in friend_requests:
                        if request.is_active:
                            raise Exception('You already sent them a friend request.')

                    friend_request = FriendRequest(sender=sender, receiver=receiver)
                    friend_request.save()
                    payload['response'] = message
                except Exception as e:
                    payload['response'] = str(e)

            except FriendRequest.DoesNotExist:
                # no existing friend request found
                friend_request = FriendRequest(sender=sender, receiver=receiver)
                friend_request.save()
                payload['response'] = message

            if payload['response'] is None:
                payload['response'] = 'Something went wrong. Try again.'
        else:
            payload['response'] = 'Unable to send a friend request.'
    else:
        payload['response'] = "You must be authenticated to send a friend request."
    return HttpResponse(json.dumps(payload), content_type="application/json")


@login_required
def view_friend_requests(request, *args, **kwargs):
    context = {}
    slug = kwargs.get('slug')
    print('viewed', slug)

    profile = Profile.objects.get(slug=slug)
    viewer = request.user
    profiles = []
    if profile.user == viewer:
        friend_requests = FriendRequest.objects.filter(receiver=viewer, is_active=True)
        context['friend_requests'] = friend_requests

        for friend_request_sender in friend_requests:
            # Get their respective profiles to load images
            profile = Profile.objects.get(user__id=friend_request_sender.sender.id)
            # print('profile found:', profile)
            profiles.append(profile)

            if get_friend_request_or_false(sender=friend_request_sender.sender, receiver=viewer):
                context['pending_friend_request_id'] = get_friend_request_or_false(
                    sender=friend_request_sender.sender, receiver=viewer).id
                print("pending", get_friend_request_or_false(sender=friend_request_sender.sender, receiver=viewer).id)

    else:
        HttpResponse("You trying to view another user's requests")
        return redirect('tongozahome:home')

    # print('profiles:', profiles)
    context['profiles'] = profiles
    return render(request, "friend/friend_requests.html", context)


@login_required
def accept_friend_request(request, *args, **kwargs):
    receiver = request.user
    payload = {}
    message = 'Friend request accepted.'
    if request.method == "GET":
        friend_request_id = kwargs.get('friend_request_id')
        if friend_request_id:
            friend_request = FriendRequest.objects.get(pk=friend_request_id)
            # confirm request
            if friend_request.receiver == receiver:
                if friend_request:
                    friend_request.accept()
                    payload['response'] = message
                else:
                    payload['response'] = "Something went wrong"
            else:
                payload['response'] = "Request is not yours to Accept"
        else:
            payload['response'] = 'Unable to accept Friend Request'
    else:
        payload['response'] = 'Login to continue'
    return HttpResponse(json.dumps(payload), content_type="application/json")


@login_required
def view_friends(request, *args, **kwargs):
    viewer = request.user
    print('viewer', viewer)

    context = {}
    slug = kwargs.get('slug')
    viewed_profile = Profile.objects.get(slug=slug)
    print('viewed profile of friends', viewed_profile)

    profiles = []
    friend_list = FriendList.objects.get(user=viewed_profile.user)
    print('friend_list', friend_list)
    friends = friend_list.friends.all()
    print('friends', friends)

    # viewer_friend_list = FriendList.objects.get(user=)

    if friends:
        context['friends'] = friends
        for friend in friends:
            # get their individual profiles
            profile = Profile.objects.get(user__id=friend.id)
            profiles.append(profile)

    is_self = True
    is_friend = False
    if viewer != viewed_profile.user:
        is_self = False

    print('is_self', is_self)
    context['is_self'] = is_self
    context['is_friend'] = is_friend
    context['profiles'] = profiles
    context['viewed_profile'] = viewed_profile
    context['viewer'] = viewer

    return render(request, "friend/friends_list.html", context)


@login_required
def remove_friend(request, *args, **kwargs):
    remover = request.user
    payload = {}
    message = 'Successfully removed'

    if request.method == "POST":
        user_id = request.POST.get("receiver_user_id")
        print('id to be removed', user_id)
        if user_id:
            try:
                removee = User.objects.get(pk=user_id)

                friend_list = FriendList.objects.get(user=remover)
                print('remover friend list', friend_list)
                friend_list.unfriend(removee)
                print('remover friend list after', friend_list)

                payload['response'] = message
            except Exception as e:
                payload['response'] = f"Something went wrong:{str(e)}."
        else:
            payload['response'] = "There was an error. Unable to remove friend."
    return HttpResponse(json.dumps(payload), content_type="application/json")


@login_required
def decline_friend_request(request, *args, **kwargs):
    decliner = request.user
    payload = {}
    if request.method == "GET":
        friend_request_id = kwargs.get("friend_request_id")
        if friend_request_id:
            friend_request = FriendRequest.objects.get(pk=friend_request_id)
            # confirm request
            if friend_request.receiver == decliner:
                if friend_request:
                    friend_request.decline()
                    payload['response'] = "Friend Request Declined!"
                else:
                    payload['response'] = "Something went wrong!"
            else:
                payload['response'] = "Not your request to decline"
        else:
            payload['response'] = "Unable to declice friend request."
    return HttpResponse(json.dumps(payload), content_type="application/json")


@login_required
def cancel_friend_request(request, *args, **kwargs):
    canceler = request.user
    print('canceler', canceler.id)
    payload = {}
    message = "Friend request cancelled"

    if request.method == "POST":
        user_id = request.POST.get("receiver_user_id")
        print('id to be removed', user_id)
        if user_id:
            try:
                receiver = User.objects.get(pk=user_id)
                print('receiver:', receiver)
                friend_requests = FriendRequest.objects.filter(sender=canceler, receiver=receiver, is_active=True)
                print('friend_requests', friend_requests)
                if len(friend_requests) > 1:
                    for request in friend_requests:
                        request.cancel()
                    payload['response'] = message
                else:
                    friend_requests.first().cancel()
                    payload['response'] = message
            except Exception as e:
                payload['response'] = "Nothing to cancel. Request does not exist."
        else:
            payload['response'] = "Unable to cancel request"

    return HttpResponse(json.dumps(payload), content_type="application/json")

friend/templates/friend/snippets/accept_friend_request.html
<script type="text/javascript">
  function acceptFriendRequest(friend_request_id, uiUpdateFunction){
    var url = "{% url 'friend:accept_friend_request' friend_request_id=54545454 %}".replace("54545454",
            friend_request_id)

    $.ajax({
      type:"GET",
      dataType:"json",
      url:url,
      timeout: 5000,
      success: function(data){
        if(data.response === data.message ){

        }
        else if(data.response != null){
          alert(data.response)
        }

      },
      error: function(data){
          alert("something went wrong" )
      },
      complete: function (data){
        uiUpdateFunction()
      },


    })

  }
</script>

friend/templates/friend/snippets/cancel_friend_request.html
<script type="text/javascript">

    function cancelFriendRequest(id, uiUpdateFunction){
        payload = {
            "csrfmiddlewaretoken": "{{ csrf_token }}",
            "receiver_user_id": id,
        }
        $.ajax({
            type: "POST",
            dataType: "json",
            url: "{% url 'friend:friend_request_cancel' %}",
            timeout:5000,
            data: payload,
            success: function (data){

                if (data['response'] === data['message']){

                }
                else if (data['response'] != null){
                    alert(data['response'])
                }

            },
            error: function (data){
                alert("Something went wrong" )

            },
            complete: function (data){
                uiUpdateFunction()
            }
        })
    }

</script>

friend/templates/friend/snippets/decline_friend_request.html
<script type="text/javascript">
  function declineFriendRequest(friend_request_id, uiUpdateFunction){
    var url = "{% url 'friend:decline_friend_request' friend_request_id=54545454 %}".replace("54545454",
            friend_request_id)

    $.ajax({
      type:"GET",
      dataType:"json",
      url:url,
      timeout: 5000,
      success: function(data){
        if(data.response === data.message ){

        }
        else if(data.response != null){
          alert(data.response)
        }

      },
      error: function(data){
          alert("something went wrong" )
      },
      complete: function (data){
        uiUpdateFunction()
      },


    })

  }
</script>

friend/templates/friend/snippets/remove_friend.html
<script type="text/javascript">

    function removeFriend(id, uiUpdateFunction){
        payload = {
            "csrfmiddlewaretoken": "{{ csrf_token }}",
            "receiver_user_id": id,
        }
        $.ajax({
            type: "POST",
            dataType: "json",
            url: "{% url 'friend:remove_friend' %}",
            timeout:5000,
            data: payload,
            success: function (data){

                if (data['response'] === data['message']){

                }
                else if (data['response'] != null){
                    alert(data['response'])
                }

            },
            error: function (data){
                alert("Something went wrong" )

            },
            complete: function (data){
                uiUpdateFunction()
            }
        })
    }

</script>

friend/templates/friend/snippets/send_friend_request.html
<script type="text/javascript">

    function sendFriendRequest(id, uiUpdateFunction){
        payload = {
            "csrfmiddlewaretoken": "{{ csrf_token }}",
            "receiver_user_id": id,
        }
        $.ajax({
            type: "POST",
            dataType: "json",
            url: "{% url 'friend:friend_request' %}",
            timeout:5000,
            data: payload,
            success: function (data){

                if (data['response'] === data['message']){

                }
                else if (data['response'] != null){
                    alert(data['response'])
                }

            },
            error: function (data){
                alert("Something went wrong" )

            },
            complete: function (data){
                uiUpdateFunction()
            }
        })
    }

</script>